# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_example_editor.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDialogButtonBox, QDoubleSpinBox, QFrame, QGraphicsView,
    QGridLayout, QGroupBox, QLabel, QPushButton,
    QSizePolicy, QSpinBox, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1010, 550)
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        Form.setFont(font)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 521, 521))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.graphicsView = QGraphicsView(self.frame)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 29, 500, 481))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 10, 51, 16))
        self.gridLayoutWidget = QWidget(Form)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(550, 10, 451, 70))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_6 = QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName(u"pushButton_6")

        self.gridLayout.addWidget(self.pushButton_6, 0, 1, 1, 1)

        self.pushButton_4 = QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.gridLayout.addWidget(self.pushButton_4, 0, 0, 1, 1)

        self.pushButton_5 = QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)

        self.pushButton_3 = QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)

        self.pushButton = QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")

        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)

        self.pushButton_2 = QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)

        self.buttonBox = QDialogButtonBox(Form)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(700, 500, 131, 30))
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(680, 90, 191, 180))
        self.groupBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setFlat(False)
        self.pushButton_8 = QPushButton(self.groupBox)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(120, 70, 51, 51))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(24)
        self.pushButton_8.setFont(font1)
        self.pushButton_7 = QPushButton(self.groupBox)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(70, 20, 51, 51))
        self.pushButton_7.setFont(font1)
        self.pushButton_9 = QPushButton(self.groupBox)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(70, 120, 51, 51))
        self.pushButton_9.setFont(font1)
        self.pushButton_10 = QPushButton(self.groupBox)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(20, 70, 51, 51))
        self.pushButton_10.setFont(font1)
        self.ui_extra_settings_group = QGroupBox(Form)
        self.ui_extra_settings_group.setObjectName(u"ui_extra_settings_group")
        self.ui_extra_settings_group.setGeometry(QRect(790, 300, 201, 161))
        self.ui_extra_settings_group.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ui_extra_settings_group.setFlat(True)
        self.ui_extra_settings_group.setCheckable(False)
        self.ui_checkbox_hq_color = QCheckBox(self.ui_extra_settings_group)
        self.ui_checkbox_hq_color.setObjectName(u"ui_checkbox_hq_color")
        self.ui_checkbox_hq_color.setGeometry(QRect(0, 20, 81, 21))
        self.ui_checkbox_hq_color.setChecked(True)
        self.ui_checkbox_hq_color.setAutoRepeat(False)
        self.ui_checkbox_variable_delay = QCheckBox(self.ui_extra_settings_group)
        self.ui_checkbox_variable_delay.setObjectName(u"ui_checkbox_variable_delay")
        self.ui_checkbox_variable_delay.setGeometry(QRect(0, 50, 101, 21))
        self.ui_checkbox_variable_delay.setChecked(False)
        self.ui_checkbox_variable_delay.setAutoRepeat(False)
        self.ui_extraction_settings_group = QGroupBox(Form)
        self.ui_extraction_settings_group.setObjectName(u"ui_extraction_settings_group")
        self.ui_extraction_settings_group.setGeometry(QRect(560, 300, 201, 181))
        self.ui_extraction_settings_group.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ui_extraction_settings_group.setFlat(True)
        self.ui_extraction_settings_group.setCheckable(False)
        self.ui_stepper_framerate = QSpinBox(self.ui_extraction_settings_group)
        self.ui_stepper_framerate.setObjectName(u"ui_stepper_framerate")
        self.ui_stepper_framerate.setGeometry(QRect(110, 30, 88, 22))
        self.ui_stepper_framerate.setFrame(False)
        self.ui_stepper_framerate.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ui_stepper_framerate.setAccelerated(False)
        self.ui_stepper_framerate.setProperty(u"showGroupSeparator", False)
        self.ui_stepper_framerate.setMaximum(999)
        self.ui_stepper_framerate.setValue(24)
        self.ui_stepper_loopdelay = QSpinBox(self.ui_extraction_settings_group)
        self.ui_stepper_loopdelay.setObjectName(u"ui_stepper_loopdelay")
        self.ui_stepper_loopdelay.setGeometry(QRect(110, 60, 88, 21))
        self.ui_stepper_loopdelay.setWrapping(False)
        self.ui_stepper_loopdelay.setFrame(False)
        self.ui_stepper_loopdelay.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ui_stepper_loopdelay.setMaximum(999)
        self.ui_stepper_loopdelay.setValue(250)
        self.ui_stepper_loopdelay.setDisplayIntegerBase(10)
        self.ui_stepper_alpha_threshold = QDoubleSpinBox(self.ui_extraction_settings_group)
        self.ui_stepper_alpha_threshold.setObjectName(u"ui_stepper_alpha_threshold")
        self.ui_stepper_alpha_threshold.setGeometry(QRect(110, 90, 88, 22))
        self.ui_stepper_alpha_threshold.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.ui_stepper_alpha_threshold.setFrame(False)
        self.ui_stepper_alpha_threshold.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ui_stepper_alpha_threshold.setMaximum(1.000000000000000)
        self.ui_stepper_alpha_threshold.setSingleStep(0.010000000000000)
        self.ui_stepper_alpha_threshold.setValue(0.500000000000000)
        self.ui_label_framerate = QLabel(self.ui_extraction_settings_group)
        self.ui_label_framerate.setObjectName(u"ui_label_framerate")
        self.ui_label_framerate.setGeometry(QRect(10, 30, 101, 21))
        self.ui_label_framerate.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ui_label_loopdelay = QLabel(self.ui_extraction_settings_group)
        self.ui_label_loopdelay.setObjectName(u"ui_label_loopdelay")
        self.ui_label_loopdelay.setGeometry(QRect(10, 60, 91, 21))
        self.ui_label_loopdelay.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ui_label_alpha_threshold = QLabel(self.ui_extraction_settings_group)
        self.ui_label_alpha_threshold.setObjectName(u"ui_label_alpha_threshold")
        self.ui_label_alpha_threshold.setGeometry(QRect(10, 90, 91, 21))
        self.ui_label_alpha_threshold.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ui_label_scale = QLabel(self.ui_extraction_settings_group)
        self.ui_label_scale.setObjectName(u"ui_label_scale")
        self.ui_label_scale.setGeometry(QRect(10, 120, 91, 21))
        self.ui_label_scale.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ui_stepper_scale = QDoubleSpinBox(self.ui_extraction_settings_group)
        self.ui_stepper_scale.setObjectName(u"ui_stepper_scale")
        self.ui_stepper_scale.setGeometry(QRect(110, 120, 88, 22))
        self.ui_stepper_scale.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.ui_stepper_scale.setFrame(False)
        self.ui_stepper_scale.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ui_stepper_scale.setMaximum(10.000000000000000)
        self.ui_stepper_scale.setSingleStep(0.010000000000000)
        self.ui_stepper_scale.setValue(1.000000000000000)
        self.ui_label_resample_filter = QLabel(self.ui_extraction_settings_group)
        self.ui_label_resample_filter.setObjectName(u"ui_label_resample_filter")
        self.ui_label_resample_filter.setGeometry(QRect(10, 150, 101, 21))
        self.ui_label_resample_filter.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.ui_dropdown_resample_filter = QComboBox(self.ui_extraction_settings_group)
        self.ui_dropdown_resample_filter.addItem("")
        self.ui_dropdown_resample_filter.addItem("")
        self.ui_dropdown_resample_filter.addItem("")
        self.ui_dropdown_resample_filter.addItem("")
        self.ui_dropdown_resample_filter.setObjectName(u"ui_dropdown_resample_filter")
        self.ui_dropdown_resample_filter.setGeometry(QRect(110, 150, 88, 22))
        self.ui_dropdown_resample_filter.setDuplicatesEnabled(False)
        self.ui_dropdown_resample_filter.setFrame(True)

        self.retranslateUi(Form)

        self.ui_dropdown_resample_filter.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Preview", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"Next. Frame", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"Prev. Frame", None))
        self.pushButton_5.setText(QCoreApplication.translate("Form", u"Play", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"Stop", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Pause", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Delete Frame", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"Adjust frame position", None))
        self.pushButton_8.setText(QCoreApplication.translate("Form", u"\u2192", None))
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"\u2191", None))
        self.pushButton_9.setText(QCoreApplication.translate("Form", u"\u2193", None))
        self.pushButton_10.setText(QCoreApplication.translate("Form", u"\u2190", None))
#if QT_CONFIG(statustip)
        self.ui_extra_settings_group.setStatusTip(QCoreApplication.translate("Form", u"Other settings that may be useful.", None))
#endif // QT_CONFIG(statustip)
        self.ui_extra_settings_group.setTitle(QCoreApplication.translate("Form", u"Extra Settings", None))
#if QT_CONFIG(statustip)
        self.ui_checkbox_hq_color.setStatusTip(QCoreApplication.translate("Form", u"Enables a better color algorithm for GIFs.", None))
#endif // QT_CONFIG(statustip)
        self.ui_checkbox_hq_color.setText(QCoreApplication.translate("Form", u"HQ Colors", None))
#if QT_CONFIG(statustip)
        self.ui_checkbox_variable_delay.setStatusTip(QCoreApplication.translate("Form", u"Modify some frame delays slightly to get a more accurate fps result.", None))
#endif // QT_CONFIG(statustip)
        self.ui_checkbox_variable_delay.setText(QCoreApplication.translate("Form", u"Variable Delay", None))
#if QT_CONFIG(statustip)
        self.ui_extraction_settings_group.setStatusTip(QCoreApplication.translate("Form", u" Global settings are applied to all animated images unless you choose to override for a specific animation.", None))
#endif // QT_CONFIG(statustip)
        self.ui_extraction_settings_group.setTitle(QCoreApplication.translate("Form", u"Animation Settings", None))
#if QT_CONFIG(statustip)
        self.ui_stepper_framerate.setStatusTip(QCoreApplication.translate("Form", u"Sets the frame rate of the animation. (NOTE: The 'FPS' is converted to 'ms' and rounded to the nearest whole number).", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.ui_stepper_loopdelay.setStatusTip(QCoreApplication.translate("Form", u"Sets how long the last frame of the animation should be shown. (Recommended values 250-500ms).", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.ui_stepper_alpha_threshold.setStatusTip(QCoreApplication.translate("Form", u"Sets the transparency threshold. Leave value at '0.50' if you're unsure. (GIFs only!).", None))
#endif // QT_CONFIG(statustip)
        self.ui_stepper_alpha_threshold.setPrefix("")
#if QT_CONFIG(statustip)
        self.ui_label_framerate.setStatusTip(QCoreApplication.translate("Form", u"Sets the frame rate of the animation. (NOTE: The 'FPS' is converted to 'ms' and rounded to the nearest whole number).", None))
#endif // QT_CONFIG(statustip)
        self.ui_label_framerate.setText(QCoreApplication.translate("Form", u"Frame Rate (FPS):", None))
#if QT_CONFIG(statustip)
        self.ui_label_loopdelay.setStatusTip(QCoreApplication.translate("Form", u"Sets how long the last frame of the animation should be shown. (Recommended values 250-500ms).", None))
#endif // QT_CONFIG(statustip)
        self.ui_label_loopdelay.setText(QCoreApplication.translate("Form", u"Loop Delay (ms):", None))
#if QT_CONFIG(statustip)
        self.ui_label_alpha_threshold.setStatusTip(QCoreApplication.translate("Form", u"Sets the transparency threshold. Leave value at '0.50' if you're unsure. (GIFs only!).", None))
#endif // QT_CONFIG(statustip)
        self.ui_label_alpha_threshold.setText(QCoreApplication.translate("Form", u"Alpha Threshold:", None))
#if QT_CONFIG(statustip)
        self.ui_label_scale.setStatusTip(QCoreApplication.translate("Form", u"Sets the image scale of generated animations.", None))
#endif // QT_CONFIG(statustip)
        self.ui_label_scale.setText(QCoreApplication.translate("Form", u"Scale:", None))
#if QT_CONFIG(statustip)
        self.ui_stepper_scale.setStatusTip(QCoreApplication.translate("Form", u"Sets the image scale of generated animations.", None))
#endif // QT_CONFIG(statustip)
        self.ui_stepper_scale.setPrefix("")
#if QT_CONFIG(statustip)
        self.ui_label_resample_filter.setStatusTip(QCoreApplication.translate("Form", u"What algorithm to use when scaling images. Choose \"Nearest\" for pixel artstyle sprites, otherwise leave at default if unsure.", None))
#endif // QT_CONFIG(statustip)
        self.ui_label_resample_filter.setText(QCoreApplication.translate("Form", u"Resample Filter:", None))
        self.ui_dropdown_resample_filter.setItemText(0, QCoreApplication.translate("Form", u"Nearest", None))
        self.ui_dropdown_resample_filter.setItemText(1, QCoreApplication.translate("Form", u"Bilinear", None))
        self.ui_dropdown_resample_filter.setItemText(2, QCoreApplication.translate("Form", u"Bicubic", None))
        self.ui_dropdown_resample_filter.setItemText(3, QCoreApplication.translate("Form", u"Lanczos", None))

#if QT_CONFIG(statustip)
        self.ui_dropdown_resample_filter.setStatusTip(QCoreApplication.translate("Form", u"What algorithm to use when scaling images. Choose \"Nearest\" for pixel artstyle sprites, otherwise leave at default if unsure.", None))
#endif // QT_CONFIG(statustip)
    # retranslateUi

