"""List of Qt-supported languages for translation dropdowns."""

from typing import List, Tuple

# Auto-generated via PySide6 QLocale metadata. Codes use QLocale.languageToCode outputs.
QT_LANGUAGE_CHOICES: List[Tuple[str, str]] = [
    ("AA", "Afar"),
    ("AB", "Abkhazian"),
    ("AE", "Avestan"),
    ("AF", "Afrikaans"),
    ("AGQ", "Aghem"),
    ("AK", "Akan"),
    ("AKK", "Akkadian"),
    ("AM", "Amharic"),
    ("AN", "Aragonese"),
    ("ANN", "Obolo"),
    ("AR", "Arabic"),
    ("ARC", "Aramaic"),
    ("ARN", "Mapuche"),
    ("AS", "Assamese"),
    ("ASA", "Asu"),
    ("ASE", "American Sign Language"),
    ("AST", "Asturian"),
    ("AV", "Avaric"),
    ("AY", "Aymara"),
    ("AZ", "Azerbaijani"),
    ("BA", "Bashkir"),
    ("BAL", "Baluchi"),
    ("BAN", "Balinese"),
    ("BAS", "Basaa"),
    ("BAX", "Bamun"),
    ("BBC", "Batak Toba"),
    ("BE", "Belarusian"),
    ("BEM", "Bemba"),
    ("BEZ", "Bena"),
    ("BG", "Bulgarian"),
    ("BGC", "Haryanvi"),
    ("BGN", "Western Balochi"),
    ("BHO", "Bhojpuri"),
    ("BI", "Bislama"),
    ("BLO", "Anii"),
    ("BLT", "Tai Dam"),
    ("BM", "Bambara"),
    ("BN", "Bangla"),
    ("BO", "Tibetan"),
    ("BR", "Breton"),
    ("BRX", "Bodo"),
    ("BS", "Bosnian"),
    ("BSS", "Akoose"),
    ("BUG", "Buginese"),
    ("BYN", "Blin"),
    ("CA", "Catalan"),
    ("CCH", "Atsam"),
    ("CCP", "Chakma"),
    ("CE", "Chechen"),
    ("CEB", "Cebuano"),
    ("CGG", "Chiga"),
    ("CH", "Chamorro"),
    ("CHR", "Cherokee"),
    ("CIC", "Chickasaw"),
    ("CKB", "Central Kurdish"),
    ("CO", "Corsican"),
    ("COP", "Coptic"),
    ("CR", "Cree"),
    ("CS", "Czech"),
    ("CSW", "Swampy Cree"),
    ("CU", "Church Slavic"),
    ("CV", "Chuvash"),
    ("CY", "Welsh"),
    ("DA", "Danish"),
    ("DAV", "Taita"),
    ("DE", "German"),
    ("DJE", "Zarma"),
    ("DOI", "Dogri"),
    ("DSB", "Lower Sorbian"),
    ("DUA", "Duala"),
    ("DV", "Divehi"),
    ("DYO", "Jola-Fonyi"),
    ("DZ", "Dzongkha"),
    ("EBU", "Embu"),
    ("EE", "Ewe"),
    ("EGY", "Ancient Egyptian"),
    ("EL", "Greek"),
    ("EN", "English"),
    ("EO", "Esperanto"),
    ("ES", "Spanish"),
    ("ET", "Estonian"),
    ("EU", "Basque"),
    ("EWO", "Ewondo"),
    ("FA", "Persian"),
    ("FF", "Fula"),
    ("FI", "Finnish"),
    ("FIL", "Filipino"),
    ("FJ", "Fijian"),
    ("FO", "Faroese"),
    ("FR", "French"),
    ("FRR", "Northern Frisian"),
    ("FUR", "Friulian"),
    ("FY", "Western Frisian"),
    ("GA", "Irish"),
    ("GAA", "Ga"),
    ("GD", "Scottish Gaelic"),
    ("GEZ", "Geez"),
    ("GL", "Galician"),
    ("GN", "Guarani"),
    ("GOT", "Gothic"),
    ("GRC", "Ancient Greek"),
    ("GSW", "Swiss German"),
    ("GU", "Gujarati"),
    ("GUZ", "Gusii"),
    ("GV", "Manx"),
    ("HA", "Hausa"),
    ("HAW", "Hawaiian"),
    ("HE", "Hebrew"),
    ("HI", "Hindi"),
    ("HO", "Hiri Motu"),
    ("HR", "Croatian"),
    ("HSB", "Upper Sorbian"),
    ("HT", "Haitian Creole"),
    ("HU", "Hungarian"),
    ("HY", "Armenian"),
    ("HZ", "Herero"),
    ("IA", "Interlingua"),
    ("ID", "Indonesian"),
    ("IE", "Interlingue"),
    ("IG", "Igbo"),
    ("II", "Sichuan Yi"),
    ("IK", "Inupiaq"),
    ("INH", "Ingush"),
    ("IO", "Ido"),
    ("IS", "Icelandic"),
    ("IT", "Italian"),
    ("IU", "Inuktitut"),
    ("JA", "Japanese"),
    ("JBO", "Lojban"),
    ("JGO", "Ngomba"),
    ("JMC", "Machame"),
    ("JV", "Javanese"),
    ("KA", "Georgian"),
    ("KAA", "Kara-Kalpak"),
    ("KAB", "Kabyle"),
    ("KAJ", "Jju"),
    ("KAM", "Kamba"),
    ("KCG", "Tyap"),
    ("KDE", "Makonde"),
    ("KEA", "Kabuverdianu"),
    ("KEN", "Kenyang"),
    ("KFO", "Koro"),
    ("KG", "Kongo"),
    ("KGP", "Kaingang"),
    ("KHQ", "Koyra Chiini"),
    ("KI", "Kikuyu"),
    ("KJ", "Kuanyama"),
    ("KK", "Kazakh"),
    ("KKJ", "Kako"),
    ("KL", "Kalaallisut"),
    ("KLN", "Kalenjin"),
    ("KM", "Khmer"),
    ("KN", "Kannada"),
    ("KO", "Korean"),
    ("KOK", "Konkani"),
    ("KPE", "Kpelle"),
    ("KR", "Kanuri"),
    ("KS", "Kashmiri"),
    ("KSB", "Shambala"),
    ("KSF", "Bafia"),
    ("KSH", "Colognian"),
    ("KU", "Kurdish"),
    ("KV", "Komi"),
    ("KW", "Cornish"),
    ("KXV", "Kuvi"),
    ("KY", "Kyrgyz"),
    ("LA", "Latin"),
    ("LAG", "Langi"),
    ("LB", "Luxembourgish"),
    ("LEZ", "Lezghian"),
    ("LG", "Ganda"),
    ("LI", "Limburgish"),
    ("LIJ", "Ligurian"),
    ("LKT", "Lakota"),
    ("LN", "Lingala"),
    ("LO", "Lao"),
    ("LRC", "Northern Luri"),
    ("LT", "Lithuanian"),
    ("LU", "Luba-Katanga"),
    ("LUO", "Luo"),
    ("LUY", "Luyia"),
    ("LV", "Latvian"),
    ("LZH", "Literary Chinese"),
    ("MAI", "Maithili"),
    ("MAN", "Mandingo"),
    ("MAS", "Masai"),
    ("MDF", "Moksha"),
    ("MEN", "Mende"),
    ("MER", "Meru"),
    ("MFE", "Morisyen"),
    ("MG", "Malagasy"),
    ("MGH", "Makhuwa-Meetto"),
    ("MGO", "Meta\u02bc"),
    ("MH", "Marshallese"),
    ("MI", "M\u0101ori"),
    ("MK", "Macedonian"),
    ("ML", "Malayalam"),
    ("MN", "Mongolian"),
    ("MNI", "Manipuri"),
    ("MOH", "Mohawk"),
    ("MR", "Marathi"),
    ("MS", "Malay"),
    ("MT", "Maltese"),
    ("MUA", "Mundang"),
    ("MUS", "Muscogee"),
    ("MY", "Burmese"),
    ("MYV", "Erzya"),
    ("MZN", "Mazanderani"),
    ("NA", "Nauru"),
    ("NAQ", "Nama"),
    ("NB", "Norwegian Bokm\xe5l"),
    ("ND", "North Ndebele"),
    ("NDS", "Low German"),
    ("NE", "Nepali"),
    ("NEW", "Newari"),
    ("NG", "Ndonga"),
    ("NL", "Dutch"),
    ("NMG", "Kwasio"),
    ("NN", "Norwegian Nynorsk"),
    ("NNH", "Ngiemboon"),
    ("NON", "Old Norse"),
    ("NQO", "N\u2019Ko"),
    ("NR", "South Ndebele"),
    ("NSO", "Northern Sotho"),
    ("NUS", "Nuer"),
    ("NV", "Navajo"),
    ("NY", "Nyanja"),
    ("NYN", "Nyankole"),
    ("OC", "Occitan"),
    ("OJ", "Ojibwa"),
    ("OM", "Oromo"),
    ("OR", "Odia"),
    ("OS", "Ossetic"),
    ("OSA", "Osage"),
    ("PA", "Punjabi"),
    ("PAL", "Pahlavi"),
    ("PAP", "Papiamento"),
    ("PAU", "Palauan"),
    ("PCM", "Nigerian Pidgin"),
    ("PEO", "Old Persian"),
    ("PHN", "Phoenician"),
    ("PI", "Pali"),
    ("PIS", "Pijin"),
    ("PL", "Polish"),
    ("PRG", "Prussian"),
    ("PS", "Pashto"),
    ("PT", "Portuguese"),
    ("QU", "Quechua"),
    ("QUC", "K\u02bciche\u02bc"),
    ("RAJ", "Rajasthani"),
    ("RHG", "Rohingya"),
    ("RM", "Romansh"),
    ("RN", "Rundi"),
    ("RO", "Romanian"),
    ("ROF", "Rombo"),
    ("RU", "Russian"),
    ("RW", "Kinyarwanda"),
    ("RWK", "Rwa"),
    ("SA", "Sanskrit"),
    ("SAH", "Yakut"),
    ("SAQ", "Samburu"),
    ("SAT", "Santali"),
    ("SAZ", "Saurashtra"),
    ("SBP", "Sangu"),
    ("SC", "Sardinian"),
    ("SCN", "Sicilian"),
    ("SD", "Sindhi"),
    ("SDH", "Southern Kurdish"),
    ("SE", "Northern Sami"),
    ("SEH", "Sena"),
    ("SES", "Koyraboro Senni"),
    ("SG", "Sango"),
    ("SGA", "Old Irish"),
    ("SHI", "Tachelhit"),
    ("SI", "Sinhala"),
    ("SID", "Sidamo"),
    ("SK", "Slovak"),
    ("SL", "Slovenian"),
    ("SM", "Samoan"),
    ("SMA", "Southern Sami"),
    ("SMJ", "Lule Sami"),
    ("SMN", "Inari Sami"),
    ("SMS", "Skolt Sami"),
    ("SN", "Shona"),
    ("SO", "Somali"),
    ("SQ", "Albanian"),
    ("SR", "Serbian"),
    ("SS", "Swati"),
    ("SSY", "Saho"),
    ("ST", "Southern Sotho"),
    ("SU", "Sundanese"),
    ("SV", "Swedish"),
    ("SW", "Swahili"),
    ("SYR", "Syriac"),
    ("SZL", "Silesian"),
    ("TA", "Tamil"),
    ("TE", "Telugu"),
    ("TEO", "Teso"),
    ("TG", "Tajik"),
    ("TH", "Thai"),
    ("TI", "Tigrinya"),
    ("TIG", "Tigre"),
    ("TK", "Turkmen"),
    ("TKL", "Tokelau"),
    ("TN", "Tswana"),
    ("TO", "Tongan"),
    ("TOK", "Toki Pona"),
    ("TPI", "Tok Pisin"),
    ("TR", "Turkish"),
    ("TRV", "Taroko"),
    ("TRW", "Torwali"),
    ("TS", "Tsonga"),
    ("TT", "Tatar"),
    ("TVL", "Tuvalu"),
    ("TWQ", "Tasawaq"),
    ("TY", "Tahitian"),
    ("TZM", "Central Atlas Tamazight"),
    ("UG", "Uyghur"),
    ("UGA", "Ugaritic"),
    ("UK", "Ukrainian"),
    ("UR", "Urdu"),
    ("UZ", "Uzbek"),
    ("VAI", "Vai"),
    ("VE", "Venda"),
    ("VEC", "Venetian"),
    ("VI", "Vietnamese"),
    ("VO", "Volap\xfck"),
    ("VUN", "Vunjo"),
    ("WA", "Walloon"),
    ("WAE", "Walser"),
    ("WAL", "Wolaytta"),
    ("WBP", "Warlpiri"),
    ("WO", "Wolof"),
    ("XH", "Xhosa"),
    ("XNR", "Kangri"),
    ("XOG", "Soga"),
    ("YAV", "Yangben"),
    ("YI", "Yiddish"),
    ("YO", "Yoruba"),
    ("YRL", "Nheengatu"),
    ("YUE", "Cantonese"),
    ("ZA", "Zhuang"),
    ("ZGH", "Standard Moroccan Tamazight"),
    ("ZH", "Chinese"),
    ("ZU", "Zulu"),
]
